import { CVData } from '@/types/cv';

export const sampleCVData: CVData = {
  id: 'sample',
  name: 'Sara Lawrence',
  title: 'Design',
  location: 'San Francisco',
  website: 'website.com',
  avatar: '',
  about: "I'm a passionate UX designer striving to create intuitive and engaging experiences. I'm a big believer that things can always be simpler than we think.",
  workExperience: [
    {
      id: '1',
      company: 'Magic Design Co',
      role: 'Senior Designer',
      location: 'San Francisco, CA',
      startDate: '2017',
      endDate: 'Now',
    },
    {
      id: '2',
      company: 'Creative Co',
      role: 'Junior Designer',
      location: 'Atlanta, GA',
      startDate: '2015',
      endDate: '2017',
    },
    {
      id: '3',
      company: 'Design Hub',
      role: 'Intern',
      location: 'Atlanta, GA',
      startDate: '2014',
      endDate: '2015',
    },
    {
      id: '4',
      company: 'Freelance',
      role: 'Graphic Designer',
      location: 'Remote',
      startDate: '2012',
      endDate: '2014',
    },
    {
      id: '5',
      company: 'Studio X',
      role: 'Art Assistant',
      location: 'Cincinnati, OH',
      startDate: '2010',
      endDate: '2012',
    },
    {
      id: '6',
      company: 'Nonprofit Y',
      role: 'Volunteer Designer',
      location: 'Cincinnati, OH',
      startDate: '2008',
      endDate: '2010',
    },
  ],
  blog: [
    {
      id: '1',
      title: 'Exploring the Intersection of Design and Technology',
      date: '2023',
      readTime: '1 min read',
      collaborators: ['Mia', 'Leo', 'Ava'],
    },
    {
      id: '2',
      title: 'Understanding Design Hierarchies',
      date: '2023',
      readTime: '1 min read',
      collaborators: ['Alex'],
    },
    {
      id: '3',
      title: 'The Art of User-Centered Design',
      date: '2020',
      readTime: '1 min read',
    },
    {
      id: '4',
      title: 'Navigating Design Challenges',
      date: '2019',
      readTime: '1 min read',
    },
    {
      id: '5',
      title: 'Crafting Engaging User Experiences',
      date: '2018',
      readTime: '1 min read',
    },
    {
      id: '6',
      title: 'Building a Cohesive Design Language',
      date: '2018',
      readTime: '1 min read',
    },
    {
      id: '7',
      title: 'The Power of Visual Storytelling',
      date: '2017',
      readTime: '1 min read',
    },
  ],
  speaking: [
    {
      id: '1',
      title: 'Designing for accessibility',
      date: '2024',
      location: 'Los Angeles, CA',
    },
    {
      id: '2',
      title: 'How to make things super simple',
      date: '2024',
      location: 'Miami, FL',
    },
    {
      id: '3',
      title: 'Designing your career',
      date: '2023',
      location: '',
    },
  ],
  projects: [
    {
      id: '1',
      title: 'Nature walks',
      date: '2021',
    },
    {
      id: '2',
      title: 'Plant-based cookware',
      date: '2020',
    },
    {
      id: '3',
      title: 'Interactive art installation',
      date: '2019',
    },
  ],
  volunteer: [],
  certificates: [],
  education: [
    {
      id: '1',
      degree: "Master's in Interaction Design",
      institution: 'Georgia Tech',
      location: 'Atlanta, GA',
      startDate: '2010',
      endDate: '2010',
    },
    {
      id: '2',
      degree: "Bachelor's in Communication Design",
      institution: 'University of Cincinnati',
      location: 'Cincinnati, OH',
      startDate: '2006',
      endDate: '2010',
    },
  ],
  contact: {
    threads: 'username',
    figma: 'username',
    instagram: 'username',
    bluesky: 'username',
    mastodon: 'username',
    x: 'username',
  },
};
